This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./document_maitre (1).ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file document_maitre (1).acn....done (297 entries accepted, 0 rejected).
Sorting entries.....done (2730 comparisons).
Generating output file document_maitre (1).acr....done (113 lines written, 0 warnings).
Output written in document_maitre (1).acr.
Transcript written in document_maitre (1).alg.
